export enum ProductType {
  Watch = 'watch',
  Coin = 'coin',
  Ring = 'ring',
  Necklace = 'necklace',
  Bracelet = 'bracelet',
  Glasses = 'glasses',
  Belt = 'belt',
  Bag = 'bag',
  Wallet = 'wallet',
  NaturalDiamond = 'natural-diamond',
  LabGrownDiamond = 'lab-grown-diamond',
  Earrings = 'earrings',
  JewellerySets = 'jewellery-sets',
  Pendants = 'pendants',
  PinsBrooches = 'pins-brooches',
  Pens = 'pens',
  Cufflinks = 'cufflinks',
  BagCharms = 'bag-charms',
  TieClip = 'tie-clip',
  KeyChain = 'key-chain',
}

export enum GeneralField {
  Sex = 'sex',
  Year = 'year',
  Title = 'title',
  Price = 'price',
  Model = 'model',
  Currency = 'currency',
  Condition = 'condition',
  BrandId = 'brandId',
  Description = 'description',
  SerialNumber = 'serialNumber',
  CanSuggestPrice = 'canSuggestPrice',
  ReferenceNumber = 'referenceNumber',
  CustomFeatures = 'customFeatures',
}
